FROM node:current-alpine AS base
WORKDIR /base
COPY package*.json ./
RUN npm install
COPY . .

FROM node:current-alpine AS production
ENV NODE_ENV=production
WORKDIR /app
COPY --from=base /base ./

EXPOSE 3000
CMD npm run start
