apiVersion: networking.k8s.io/v1beta1 
kind: Ingress 
metadata: 
  name: sradams-co-uk-lb
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "sradams-co-uk-ip"
    kubernetes.io/ingress.allow-http: "false"
    #kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec: 
  tls:
  - secretName: sradams-co-uk-tls
  backend:
    serviceName: sradams-service
    servicePort: 3000
  rules: 
  - http: 
      paths: 
      - path: /*
        backend:
          serviceName: sradams-service
          servicePort: 3000
